# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f0c84dcfa18658faf9fab764e9639fd83c7109713f8a4837cffaadb43aacc60524b1eae8da5ab2d143593d48417c974460e8445bdabf349fa3f50da87705007

test:
  secret_key_base: cb1d5a695fc5ae9b396d9c276f38bbcee1b592be95bfa278eb59632e20d7016b388f1b42b4f2ca633d13fc313d9f9a352231291f7d634382166d069126fbb578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
